### ISSUE TITLE
Project roadmap

### ISSUE THREAD

**Issue by Gelio** [Gelio/CAL-web#42]
Outline of the project roadmap.

### Thesis scope

[Filter](https://github.com/Gelio/CAL-web/labels/thesis-required)

- [x] EMF metamodel for CAL (based on [the original data model](https://www.balticlsc.eu/model/index.htm?goto=4:2:404)) working in Sirus Desktop
- [x] CAL model working in Sirius Web (manual manipulation of the model, no extra features)
- [x] Basic model automation
  - [x] Synchronizing `ComputedDataPin`s for a `UnitCall` based on the `ComputationUnitRelease` it calls
  - [x] Removing `DataFlow`s when one of its ends is removed
- [x] Support BalticLSC toolbox (#18, https://github.com/Gelio/CAL-web/projects/3)
- [x] Semantic metamodel validation ([filter](https://github.com/Gelio/CAL-web/issues?q=is%3Aopen+label%3A%22scope%3A+model+validation%22+label%3Athesis-required), [not required](https://github.com/Gelio/CAL-web/issues?q=is%3Aopen+label%3A%22scope%3A+model+validation%22+-label%3Athesis-required))
- [x] Align CAL metamodel definitions ([filter](https://github.com/Gelio/CAL-web/issues?q=is%3Aopen+label%3Athesis-required+label%3A%22scope%3A+metamodel%22), [not required](https://github.com/Gelio/CAL-web/issues?q=is%3Aopen+label%3A%22scope%3A+metamodel%22+-label%3Athesis-required))
- [x] RFC for integrating CAL-web in BalticLSC (#41)
- [x] Write the thesis paper ([project](https://github.com/Gelio/CAL-web/projects/6), [filter](https://github.com/Gelio/CAL-web/issues?q=is%3Aopen+label%3A%22scope%3A+thesis+paper%22+label%3Athesis-required), [not required](https://github.com/Gelio/CAL-web/issues?q=is%3Aopen+label%3A%22scope%3A+thesis+paper%22+-label%3Athesis-required))

### Out of thesis scope

- [ ] BalticLSC data model integration
  - [ ] Create a Sirius Web model based on BalticLSC model
  - [ ] Per-user model visibility (#35)
  - [ ] Export a Sirius Web model to a BalticLSC model
- [ ] BalticLSC frontend integration
