### ISSUE TITLE
Use user information encoded in BalticLSC JWT to create accounts on-demand

### ISSUE THREAD

**Issue by Gelio** [Gelio/CAL-web#96]
The BalticLSC JWT provided to the workbench has information about the user to whom this JWT belongs:

![image](https://user-images.githubusercontent.com/889383/143405852-b846c519-f5f4-4e97-b6d0-097755b56e92.png)

For an example, use the following on https://jwt.io/:

```
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImRlbW8iLCJzdWIiOiJkZW1vIiwianRpIjoiYTRlMTZjYTVmMTgwNDg4NDllN2FlYTkzYjUwYWI1MmEiLCJzaWQiOiI4ZmM3NzVkZGQ1ZDc0OGYwOTZhNmI3OTFkMzRjZWQ5YyIsImV4cCI6MTYzNzgzMTk1NiwiaXNzIjoid3V0LmJhbHRpY2xzYy5ldSIsImF1ZCI6Ind1dC5iYWx0aWNsc2MuZXUifQ.EYvLg05pWDK2tIBbMQjMww09tYt5QbxlcdzKAx_BQ5g
```

We can use that information to create a user account on-demand and use it to then create user-scoped projects.

See https://github.com/Gelio/CAL-web/issues/35#issuecomment-978925757 for a description of how authentication worked in Sirius Web prior to this change.

## Changes required

1. In the UI, the JWT should be provided before showing a list of projects. This is because projects are scoped to a specific user.

	This means the user should be able to modify the authentication token on the project list page in case they want to "log in" as a different user.

1. The viewer in Sirius Web should correspond to the `sub` field in the JWT

	https://github.com/Gelio/CAL-web/blob/7571e5bcc4bf78ea45be9fa8a214215186824796/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/services/ViewerProvider.java#L31-L37

1. We need to restrict access to projects per user. Only the project owner should be able to see it.

	https://github.com/Gelio/CAL-web/blob/7571e5bcc4bf78ea45be9fa8a214215186824796/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/services/ProjectAccessPolicy.java#L28-L45

1. The default user is no longer needed

	https://github.com/Gelio/CAL-web/blob/7571e5bcc4bf78ea45be9fa8a214215186824796/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/filters/SiriusWebAuthenticationFilter.java#L45-L72

	https://github.com/Gelio/CAL-web/blob/7571e5bcc4bf78ea45be9fa8a214215186824796/backend/sirius-web-persistence/src/main/resources/db/changelog/sirius-web-schema.sql#L92-L94

1. Remove the `httpBasic` authentication https://github.com/Gelio/CAL-web/blob/7571e5bcc4bf78ea45be9fa8a214215186824796/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/configuration/SpringWebSecurityConfiguration.java#L52 and use a new [_security filter_](https://docs.spring.io/spring-security/reference/servlet/architecture.html#servlet-security-filters) that will extract the `sub` from the provided JWT.

	Maybe we could use [`BearerTokenAuthenticationFilter`](https://docs.spring.io/spring-security/site/docs/current/api/org/springframework/security/oauth2/server/resource/web/BearerTokenAuthenticationFilter.html) to avoid having to parse the JWT manually, as is done in [this tutorial](https://www.toptal.com/spring/spring-security-tutorial).

	We will not be able to fully validate the JWT because we don't have the secret that is required to validate the JWT's signature. We can skip it for now and create an issue for it, and also mention it as a possible enhancement in the future. This is related to #95.

	See https://stackoverflow.com/questions/41975045/how-to-design-a-good-jwt-authentication-filter for an example JWT filter. It uses the [JJWT](https://github.com/jwtk/jjwt) library.

	[This tutorial](https://www.toptal.com/spring/spring-security-tutorial) is also a good resource about Java Spring authentication.

1. When looking up a user by username, if the account does not exist, we need to create it to allow new users 

	https://github.com/Gelio/CAL-web/blob/7571e5bcc4bf78ea45be9fa8a214215186824796/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/configuration/SpringWebSecurityConfiguration.java#L59-L61

## To do

- [x] Add support for extracting `sub` from JWT and dynamically creating accounts in the server. Verify that it works using GraphQL Playground.
- [x] Remove `stackTrace`s from the API error responses (reported as #98 )
- [x] Modify the frontend to allow entering a JWT at the start screen
- [x] Send the JWT with each request in the UI.
- [x] Create an issue for fully validating JWT's signature using the secret (which we don't have ATM) (reported #99)
- [x] Add a button to use the _demo_ user token automatically instead of requiring the user to sign into BalticLSC and copy the token (reported #100)
- [x] Add a task to add WebSocket authentication correctly (see https://github.com/eclipse-sirius/sirius-components/issues/846#issuecomment-981072654) (reported #101)

**Comment by Gelio** [comment]
I missed the fact that the `Authorization` header is not passed when using WebSockets. There is no way to tell which user is connected using WebSockets.

I configured `connectionParams` for `WebSocketLink`:

```ts
      connectionParams: () => ({
        // https://github.com/apollographql/apollo-client/issues/3967#issuecomment-450255702
        headers: getAuthHeaders(token),
      }),
```

but they are sent in the `connection_init` message:

![image](https://user-images.githubusercontent.com/889383/143681432-02d11013-137c-4688-969f-f54e5c52aacf.png)


I need to find a way to extract the token from the `connection_init` message and set `principal` on Spring's `WebSocketSession` (which is later used in https://github.com/eclipse-sirius/sirius-components/blob/ab8097c6c3593f10fdd16f9212762624a3639ccc/backend/sirius-web-spring-graphql/src/main/java/org/eclipse/sirius/web/spring/graphql/ws/GraphQLWebSocketHandler.java#L242-L244 to check who the user is).

**Comment by Gelio** [comment]
It seems to me it's not possible to add authentication to WebSocket connections without modifications to the `sirius-components` library.

I have reported the problem upstream https://github.com/eclipse-sirius/sirius-components/issues/846

I suppose I could verify that the `SiriusWebAuthenticationFilter` hack of injecting `Authorization` headers into all requests indeed is causing problems and then update the upstream issue. I could do that by removing `SiriusWebAuthenticationFilter` and instead let the frontend send the headers it injects.

After I do that, I will park this issue until the upstream problem is resolved.

**Comment by Gelio** [comment]
I have modified the original version of Sirius Web and moved the `Authorization` header to the frontend

https://github.com/Gelio/sirius-web/commit/27d862c1796546ca64dc2adeb577991e26a114ec

GraphQL queries and mutations now require the header (which is expected). GraphQL subscriptions do not need any header to work. This is not what I am seeing on https://github.com/Gelio/CAL-web/pull/97 where I am getting `connection_error` responses via WebSocket.

**Comment by Gelio** [comment]
I managed to find a workaround that allows using GraphQL Subscriptions without authentication: https://github.com/Gelio/CAL-web/pull/97/commits/2b0742e22adccb3144784003ea35bb39f756f5bb

I am able to proceed with this task despite allowing read-only access to any model. This is not ideal, but at least I can proceed. I have reported my findings in https://github.com/eclipse-sirius/sirius-components/issues/846#issuecomment-981072654.

If that problem is not fixed by the time I finish this task, I should create a follow-up task to add authentication for WebSockets properly.
